import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../assets/nightwaka-dark.png";

const formatCurrency = (amount) => {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
  }).format(amount || 0);
};

const formatDate = (value) => {
  if (!value) {
    return "";
  }
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) {
    return "";
  }
  return date.toLocaleDateString("en-NG", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
};

const loadImage = (src) =>
  new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = (e) => reject(e);
    img.src = src;
  });

export const downloadAnalyticsReport = async ({ analytics, period }) => {
  if (!analytics || !analytics.range) {
    return;
  }

  const rangeStart = analytics.range.startDate
    ? new Date(analytics.range.startDate)
    : null;
  const rangeEnd = analytics.range.endDate
    ? new Date(analytics.range.endDate)
    : null;

  const formattedRangeStart = formatDate(rangeStart);
  const formattedRangeEnd = formatDate(rangeEnd);
  const periodLabel = period
    ? period.charAt(0).toUpperCase() + period.slice(1)
    : "";

  const rewardsGiven = analytics.rewards?.given || {};
  const rewardsUsed = analytics.rewards?.used || {};
  const rewardsUsedByCategory = rewardsUsed.byCategory || {};
  const rewardsBillServices = rewardsUsed.billServices || {};

  const goldDiscountTotals = analytics.goldStatus?.discounts?.total || {
    customer: 0,
    rider: 0,
    combined: 0,
  };

  const users = analytics.users || {};

  const doc = new jsPDF("p", "mm", "a4");

  try {
    const img = await loadImage(logo);
    doc.addImage(img, "PNG", 15, 10, 30, 30);
  } catch {
  }

  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("9thWaka Analytics Report", 105, 25, { align: "center" });

  doc.setFontSize(11);
  doc.setTextColor(75, 85, 99);
  doc.text(`Period: ${periodLabel}`, 105, 34, { align: "center" });

  doc.setFontSize(12);
  doc.setTextColor(220, 38, 38);
  doc.text(
    `Date range: ${formattedRangeStart} - ${formattedRangeEnd}`,
    105,
    41,
    { align: "center" }
  );

  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("Generated by 9thWaka Admin", 105, 48, { align: "center" });

  const coreMetricsBody = [
    [
      "Total revenue (commission)",
      formatCurrency(analytics.revenue?.totalCommission || 0),
    ],
    [
      "Profit (revenue minus rewards given)",
      formatCurrency(analytics.profit?.total || 0),
    ],
    [
      "Rewards given (total)",
      formatCurrency(rewardsGiven.total || 0),
    ],
    [
      "Rewards given: referral",
      formatCurrency(rewardsGiven.byType?.referral_reward || 0),
    ],
    [
      "Rewards given: streak bonus",
      formatCurrency(rewardsGiven.byType?.streak_bonus || 0),
    ],
    [
      "Rewards used: orders",
      formatCurrency(rewardsUsedByCategory.order_payment || 0),
    ],
    [
      "Rewards used: rider commissions",
      formatCurrency(rewardsUsedByCategory.commission_payment || 0),
    ],
    [
      "Rewards used: bills",
      formatCurrency(rewardsUsedByCategory.bill_payment || 0),
    ],
    [
      "Gold Status discounts (customers)",
      formatCurrency(goldDiscountTotals.customer || 0),
    ],
    [
      "Gold Status discounts (riders)",
      formatCurrency(goldDiscountTotals.rider || 0),
    ],
    [
      "Gold Status discounts (combined)",
      formatCurrency(goldDiscountTotals.combined || 0),
    ],
    [
      "Total users",
      (users.total || 0).toLocaleString("en-NG"),
    ],
    [
      "Customers",
      (users.customers || 0).toLocaleString("en-NG"),
    ],
    [
      "Riders",
      (users.riders || 0).toLocaleString("en-NG"),
    ],
  ];

  doc.autoTable({
    startY: 60,
    head: [["Metric", "Value"]],
    body: coreMetricsBody,
    styles: {
      fontSize: 9,
    },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: 255,
    },
    alternateRowStyles: {
      fillColor: [243, 244, 246],
    },
  });

  const services = Object.entries(rewardsBillServices);
  if (services.length > 0) {
    const billBody = services.map(([serviceKey, amount]) => [
      serviceKey.replace(/_/g, " "),
      formatCurrency(amount || 0),
    ]);

    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 8,
      head: [["Bill service", "Rewards used"]],
      body: billBody,
      styles: {
        fontSize: 9,
      },
      headStyles: {
        fillColor: [30, 64, 175],
        textColor: 255,
      },
      alternateRowStyles: {
        fillColor: [239, 246, 255],
      },
    });
  }

  const fileDate = new Date().toISOString().slice(0, 10);
  const safePeriod = period || "range";
  doc.save(`9thwaka-analytics-${safePeriod}-${fileDate}.pdf`);
};
